---
language: cpp
sudo: required
services:
    - docker
before_install:
    - docker build -t swearjar .
jobs:
    include:
        - stage: build and test
          script: docker run --rm -v"$PWD:/buildarea" swearjar /bin/sh -c 'mkdir -p build && cd build && cmake .. && make && make test'
