name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      submodules: true
    - name: make build directory
      run: mkdir -p build
    - name: run cmake
      working-directory: build
      run: cmake ..
    - name: build
      working-directory: build
      run: make
    - name: test
      working-directory: build
      run: ctest -V
